# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multiply a number by two
#'
#' @param x A single integer.
#' @export
Inv_F_cpp <- function(u, t0) {
    .Call(`_semicure_Inv_F_cpp`, u, t0)
}

G_gamma_cpp <- function(x, gamma) {
    .Call(`_semicure_G_gamma_cpp`, x, gamma)
}

Sfcn_cpp <- function(gamma, F_hat, beta, Z) {
    .Call(`_semicure_Sfcn_cpp`, gamma, F_hat, beta, Z)
}

