# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

G_gamma_cpp <- function(x, gamma) {
    .Call(`_semicure_G_gamma_cpp`, x, gamma)
}

G_inv_cpp <- function(y, gamma) {
    .Call(`_semicure_G_inv_cpp`, y, gamma)
}

